# Generated by Django 3.2.7 on 2021-09-16 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20210916_1154'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostComment',
        ),
    ]
